name: Add label issues
on:
  project_card:
    types:
      - moved
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: add progress label
        uses: andymckay/labeler@master
        with:
          add-labels: "IN PROGRESS"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
